name: Deploy to AWS EC2 with Docker

on:
  push:
    branches:
      - QA  # O la rama que usas para despliegues

jobs:
  deploy-instance-1:
    name: Deploy to EC2 Instance 1
    runs-on: ubuntu-latest
    steps:
      # Verificar que los secretos requeridos están configurados
      - name: Validate required secrets for Instance 1
        run: |
          if [[ -z "${{ secrets.EC2_HOST_1 }}" || -z "${{ secrets.EC2_USER }}" || -z "${{ secrets.EC2_SSH_KEY_2 }}" || -z "${{ secrets.DOCKER_USERNAME }}" ]]; then
            echo "Error: Missing one or more required secrets for Instance 1."
            exit 1
          fi

      # Conectar a la instancia EC2 y desplegar la aplicación
      - name: Deploy to EC2 - instance-1
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST_1 }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY_2 }}
          port: 22
          script: |
            # Actualizar el sistema y configurar Docker
            sudo yum update -y
            sudo yum install -y docker
            sudo service docker start
            sudo usermod -a -G docker ec2-user
            
            # Descargar la nueva imagen y detener/eliminar el contenedor actual
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/tercera-pagina:latest
            sudo docker ps -q --filter "name=tercera-pagina" | grep -q . && \
              sudo docker stop tercera-pagina && sudo docker rm tercera-pagina || true
            
            # Ejecutar el nuevo contenedor
            sudo docker run -d --name tercera-pagina -p 80:80 ${{ secrets.DOCKER_USERNAME }}/tercera-pagina:latest
