name: Deploy Docker Image to Multiple EC2 Instances

on:
  pull_request:
    branches:
      - main

jobs:
  deploy-to-ec2-instance1:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Docker Image to EC2 Instance 1
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_INSTANCE3_PUBLIC_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEYP }}
          script: |
            # Actualizar paquetes
            sudo yum update -y
            # Instalar Docker si no est치 instalado
            sudo amazon-linux-extras enable docker
            sudo yum install -y docker
            sudo service docker start
            # Descargar e iniciar la imagen desde Docker Hub
            sudo docker pull carlosdhc333/js-holamundo:qa
            sudo docker stop js-holamundo-container || true
            sudo docker rm js-holamundo-container || true
            sudo docker run -d --name js-holamundo-container -p 80:80 carlosdhc333/js-holamundo:qa

  deploy-to-ec2-instance2:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Docker Image to EC2 Instance 2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_INSTANCE4_PUBLIC_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEYP }}
          script: |
            # Actualizar paquetes
            sudo yum update -y
            # Instalar Docker si no est치 instalado
            sudo amazon-linux-extras enable docker
            sudo yum install -y docker
            sudo service docker start
            # Descargar e iniciar la imagen desde Docker Hub
            sudo docker pull carlosdhc333/js-holamundo:qa
            sudo docker stop js-holamundo-container || true
            sudo docker rm js-holamundo-container || true
            sudo docker run -d --name js-holamundo-container -p 80:80 carlosdhc333/js-holamundo:qa

  deploy-to-ec2-instance3:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Docker Image to EC2 Instance 3
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_INSTANCE5_PUBLIC_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEYP }}
          script: |
            # Actualizar paquetes
            sudo yum update -y
            # Instalar Docker si no est치 instalado
            sudo amazon-linux-extras enable docker
            sudo yum install -y docker
            sudo service docker start
            # Descargar e iniciar la imagen desde Docker Hub
            sudo docker pull carlosdhc333/js-holamundo:qa
            sudo docker stop js-holamundo-container || true
            sudo docker rm js-holamundo-container || true
            sudo docker run -d --name js-holamundo-container -p 80:80 carlosdhc333/js-holamundo:qa

  deploy-to-ec2-instance4:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Docker Image to EC2 Instance 4
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_INSTANCE6_PUBLIC_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEYP }}
          script: |
            # Actualizar paquetes
            sudo yum update -y
            # Instalar Docker si no est치 instalado
            sudo amazon-linux-extras enable docker
            sudo yum install -y docker
            sudo service docker start
            # Descargar e iniciar la imagen desde Docker Hub
            sudo docker pull carlosdhc333/js-holamundo:qa
            sudo docker stop js-holamundo-container || true
            sudo docker rm js-holamundo-container || true
            sudo docker run -d --name js-holamundo-container -p 80:80 carlosdhc333/js-holamundo:qa
