name: Deploy to AWS EC2 with Docker
 
on:
  push:
    branches:
      - QA  # O la rama que usas para despliegues
 
jobs:
  deploy-instance-1:
    name: Deploy to EC2 Instance 1
    runs-on: ubuntu-latest
 
    steps:
      # Validar que los secretos requeridos están configurados
      - name: Validate required secrets for Instance 1
        run: |
          if [[ -z "${{ secrets.EC2_HOST_1 }}" || -z "${{ secrets.EC2_USER }}" || -z "${{ secrets.EC2_SSH_KEY_2 }}" || -z "${{ secrets.DOCKER_USERNAME }}" ]]; then
            echo "Error: Missing one or more required secrets for Instance 1."
            exit 1
          fi
 
      # Construir y publicar la imagen Docker
      - name: Build and push Docker image
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/tercera-pagina"
          docker build -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:latest
 
      # Desplegar en la instancia EC2
      - name: Deploy to EC2 - instance-1
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST_1 }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY_2 }}
          port: 22
          script: |
            # Actualizar el sistema y configurar Docker
            sudo yum update -y
            sudo yum install -y docker
            sudo service docker start
            sudo usermod -a -G docker ec2-user
            # Descargar la nueva imagen y detener/eliminar el contenedor actual
            IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/tercera-pagina"
            sudo docker pull $IMAGE_NAME:latest
            sudo docker ps -q --filter "name=tercera-pagina" | grep -q . && \
              sudo docker stop tercera-pagina && sudo docker rm tercera-pagina || true
            # Ejecutar el nuevo contenedor
            sudo docker run -d --name tercera-pagina -p 80:80 $IMAGE_NAME:latest